# cloudbuild.yaml
steps:
    - name: "gcr.io/cloud-builders/gke-deploy"
      args:
      - run
      - --filename=entro-hasura-deployment.yaml
      - --location=us-central1-c
      - --cluster=prod-cluster